insert into public.product_pages (
  category_id, slug, page_type, parent_slug, parent_label,
  seo, breadcrumb, hero, hero_side, hero_ctas, spotlight, sections,
  sort_order, published
) values (
  '15ea4c42-9178-4113-ab9c-437b5be6c59e',
  'ceramic-igniters',
  'category',
  null,
  null,
  '{"title":"Ceramic Igniters | Hot Surface Ignition for OEM Appliances","description":"Explore ceramic igniters for pellet stoves, BBQ grills, gas furnaces, water heaters, and HVAC systems. UL/CE certified, OEM-ready, and long service life.","keywords":"ceramic igniter, pellet ceramic igniter"}'::jsonb,
  '[{"label":"Home","to":"/"},{"label":"Products","to":"/products"},{"label":"Ceramic Igniters"}]'::jsonb,
  '{"eyebrow":"★ Flagship Product Category","title":"Ceramic hot surface igniters,","titleHighlight":"built for OEM appliance platforms.","subtitle":"Si₃N₄, SiC, and Al₂O₃ ceramic igniters for <b>pellet stoves, BBQ grills, gas furnaces, water heaters, boilers, and HVAC platforms</b>. Our flagship CN-300 silicon nitride hot-surface igniter supports high-cycle ignition and OEM fitment, and is UL/CE certified for optimal performance.","stats":[{"num":"5","lbl":"Igniter Types"},{"num":"100K+","lbl":"Cycle Life"},{"num":"48h","lbl":"Sample Dispatch"},{"num":"42","lbl":"Export Markets"}]}'::jsonb,
  'quote',
  null,
  null,
  '[{"type":"benefits","num":"02 · Why Buy From Ceramitell","headingHtml":"What OEM buyers <span class=\"accent\">come to us for</span>.","lead":"We''re a direct manufacturer, not a trader. That means engineering answers, drop-in compatibility, and pricing that survives volume — without a middleman markup.","softBg":true,"items":[{"title":"Drop-in replacements","body":"Send a Norton 271N, White-Rodgers, or Robertshaw part number — we match voltage, power, mounting, and lead config to spec."},{"title":"Free samples, 48-hour dispatch","body":"Stock BLK SKUs ship from our Hangzhou warehouse within 48 hours — no MOQ on samples, charges credited to first order."},{"title":"UL / CE certified","body":"BLK series is UL Recognized and CE-marked for the EU. Certification scans available on request for your compliance file."},{"title":"Private-label at no extra cost","body":"Laser-marked branding on the mounting flange or housing, free on production orders of 1,000+ units. Mutual NDA standard."},{"title":"DFM on custom parts","body":"Send STEP/PDF/DWG and get a 48-hour DFM reply with material recommendation, then prototypes in 7–14 days."},{"title":"Direct-manufacturer pricing","body":"One factory, no trading layer. Stable cost at volume and engineers you can reach — not a sales desk reading from a catalog."}]},{"type":"app-uses","num":"03 · Where They Fire","headingHtml":"Appliances our igniters <span class=\"accent\">run in</span>.","lead":"From residential pellet stoves to industrial boilers — each application links to a deeper engineering page with the recommended igniter type and case data.","items":[{"icon":"🔥","title":"Pellet & Biomass Stoves","desc":"High-cycle residential heating. Our flagship application — Italian OEM ships 180,000 units/year with BLK, −38% warranty returns.","grade":"BLK Si₃N₄","to":"/applications/sub-biomass-pellet-stoves"},{"icon":"🍖","title":"BBQ & Outdoor Grills","desc":"Fast, reliable ignition for gas grills and outdoor cooking appliances. 3-second heat-up, weather-cycle durable, low-voltage variants available.","grade":"BLK / Universal","to":"/applications"},{"icon":"♨️","title":"Gas Furnaces & Water Heaters","desc":"Residential and commercial HVAC ignition. Drop-in for major Western furnace OEM igniters across 120V and 230V platforms.","grade":"BLK / Universal","to":"/applications"},{"icon":"🏭","title":"Industrial Boilers","desc":"High-temperature commercial and industrial heating. SiC hot rod handles higher surface temperatures for demanding boiler duty.","grade":"SiC Hot Rod","to":"/applications"},{"icon":"⛽","title":"Diesel & Oil Burners","desc":"Engine pre-heat, oil burner ignition, and auxiliary cabin heaters. Sealed glow-plug form factor to automotive vibration spec.","grade":"Si₃N₄ Glow Plug","to":"/applications"},{"icon":"📐","title":"Your Application","desc":"Heating or ignition need not listed? Tell us the appliance, duty cycle, and voltage — we''ll recommend a type and quote within 24 hours.","grade":"Talk to an engineer","to":"/contact"}]},{"type":"casecta"},{"type":"faq","num":"04 · Engineering FAQ","headingHtml":"The questions <span class=\"accent\">we get most</span>.","lead":"Direct answers from our application team. Need more? Email us with your part number, drawing, or duty cycle.","items":[{"q":"Can your igniters replace Norton 271N / White-Rodgers / Robertshaw?","a":"Yes — we routinely produce drop-in replacements for these and other Western OEM igniters. Send the part number, we''ll match voltage, power, mounting, and lead config. UL/CE certified for North American and EU markets."},{"q":"What''s the MOQ for custom igniters?","a":"Stock BLK SKUs: no MOQ — single-unit samples available. Custom voltage/form factor: 5,000-unit production MOQ typical. Sample charges credit against first production order."},{"q":"How fast can I get samples?","a":"Stock BLK samples dispatch within 48 hours from our Hangzhou warehouse to anywhere in our 42 export markets. Custom prototypes typically ship in 7–14 days from drawing receipt — DFM review included."},{"q":"What is a ceramic hot surface igniter?","a":"Ceramic hot-surface igniters are electrically heated ceramic components designed to reach an ignition temperature to ignite gas, biomass pellets, or liquid-fuel appliances. Ceramitell provides Si₃N₄, SiC, and Al₂O₃ hot surface igniters for OEM appliance platforms, replacement programs, and custom ignition assemblies."},{"q":"Are your igniters UL/CE certified?","a":"BLK series is UL Recognized (Component Recognition) and CE-marked for the EU. Certification scans available on request. Custom-voltage igniters require additional certification testing if outside our existing approved configurations."},{"q":"What''s the warranty?","a":"Standard warranty is 24 months from date of OEM installation against manufacturing defect. Extended warranty (36-48 months) available for OEM partnerships with annual volume commitments. Field failure analysis included."}]}]'::jsonb,
  0,
  true
) on conflict (slug) do update set
  category_id = excluded.category_id,
  page_type = excluded.page_type,
  parent_slug = excluded.parent_slug,
  parent_label = excluded.parent_label,
  seo = excluded.seo,
  breadcrumb = excluded.breadcrumb,
  hero = excluded.hero,
  hero_side = excluded.hero_side,
  hero_ctas = excluded.hero_ctas,
  spotlight = excluded.spotlight,
  sections = excluded.sections,
  sort_order = excluded.sort_order,
  published = excluded.published,
  updated_at = now();;
insert into public.product_pages (
  category_id, slug, page_type, parent_slug, parent_label,
  seo, breadcrumb, hero, hero_side, hero_ctas, spotlight, sections,
  sort_order, published
) values (
  'b2aa83f6-34d1-4430-a974-1de8637ce4e7',
  'ceramic-heaters',
  'category',
  null,
  null,
  '{"title":"Ceramic Heaters & Heating Elements | OEM Heating Solutions","description":"Ceramic heaters and heating elements for industrial heating systems requiring rapid heat-up, efficient thermal performance, and temperatures up to 1600°C.","keywords":"ceramic heaters, ceramic heating element, ceramic heating elements, ceramic heater element, ceramic heater elements, ptc ceramic heater, ptc heater ceramic, ptc ceramic heating, ceramic ptc heating"}'::jsonb,
  '[{"label":"Home","to":"/"},{"label":"Products","to":"/products"},{"label":"Ceramic Heaters"}]'::jsonb,
  '{"eyebrow":"Product Category 02 · Industrial Heating","title":"Ceramic heaters &","titleHighlight":"heating elements.","subtitle":"Si₃N₄, SiC, Al₂O₃, and AlN heating elements for industrial furnaces, semiconductor equipment, and high-temperature process engineering. Operating temperatures to <b>1600°C</b>. Custom voltages and precision geometries to OEM drawing.","stats":[{"num":"5","lbl":"Heater Types"},{"num":"1600°C","lbl":"Max Temp"},{"num":"Custom","lbl":"Voltage & Size"},{"num":"ISO 9001","lbl":"Certified"}]}'::jsonb,
  'quote',
  null,
  null,
  '[{"type":"benefits","num":"02 · Why Buy From Ceramitell","headingHtml":"What heating engineers <span class=\"accent\">come to us for</span>.","lead":"Direct manufacturer. DFM support for custom geometries. Stable supply across all four ceramic heater materials.","softBg":true,"items":[{"title":"Up to 1600°C service","body":"SiC heating elements operate continuously at 1600°C — the highest-temperature ceramic heater in our range, for glass, metal, and advanced materials furnaces."},{"title":"Custom geometry to drawing","body":"Send STEP, DWG, or PDF — DFM quote within 48 hours, prototypes in 7–14 days. Flat plates, rods, tubes, and complex profiles."},{"title":"All four ceramic materials","body":"One supplier covers Si₃N₄, SiC, Al₂O₃, and AlN heating elements — simplify your vendor list."},{"title":"Voltage-matched to your system","body":"120V/230V standard; custom DC voltages on production orders. Resistance tolerance ±5% standard, ±2% on request."},{"title":"Fast sample dispatch","body":"Stock Si₃N₄ heater samples dispatch within 48 hours. Custom prototype: 7–14 days."},{"title":"ISO 9001 quality system","body":"Full PPAP-level documentation available for OEM qualification programs."}]},{"type":"app-uses","num":"03 · Applications","headingHtml":"Where ceramic heaters <span class=\"accent\">are specified</span>.","lead":"From semiconductor wafer-chucks to industrial glass furnaces.","items":[{"icon":"🏭","title":"Industrial Furnaces","desc":"SiC and Si₃N₄ elements for glass, metal, and advanced-material furnaces above 1000°C.","grade":"SiC or Si₃N₄","to":"/applications"},{"icon":"💻","title":"Semiconductor","desc":"AlN wafer-chuck heaters for CVD/PVD chamber temperature control.","grade":"AlN Heaters","to":"/applications"},{"icon":"🧪","title":"Laboratory Equipment","desc":"Al₂O₃ tube-furnace elements and muffle furnace heaters for analytical instruments.","grade":"Al₂O₃ Heaters","to":"/applications"},{"icon":"⚗️","title":"Chemical Processing","desc":"Si₃N₄ immersion heaters for corrosive fluid heating and chemical bath control.","grade":"Si₃N₄ Heaters","to":"/applications"},{"icon":"🔥","title":"Appliances & Ignition","desc":"Si₃N₄ flat heaters for residential pellet stove ignition and auxiliary heating.","grade":"Si₃N₄ Heaters","to":"/applications"},{"icon":"📐","title":"Custom Application","desc":"Send your spec — we recommend material, geometry, and voltage within 48 hours.","grade":"Contact an engineer","to":"/applications"}]},{"type":"faq","num":"04 · FAQ","headingHtml":"The questions <span class=\"accent\">we get most</span>.","softBg":true,"items":[{"q":"Max operating temperature?","a":"SiC: 1600°C. Si₃N₄: 1300°C surface. Al₂O₃: 1200°C. AlN: 800°C for precision apps."},{"q":"Can you match my heater geometry?","a":"Send STEP/DWG/PDF — DFM review and quote within 48 hours."},{"q":"What voltages are available?","a":"120V/230V AC standard. Custom DC on production orders."},{"q":"Sample lead time?","a":"Stock Si₃N₄: 48h. Custom prototype: 7–14 days."},{"q":"OEM/private-label?","a":"Laser marking on metal components, free on production orders of 500+ units."},{"q":"Certifications?","a":"ISO 9001. CE marking for EU. RoHS/REACH declarations. PPAP available."}]},{"type":"casecta"}]'::jsonb,
  1,
  true
) on conflict (slug) do update set
  category_id = excluded.category_id,
  page_type = excluded.page_type,
  parent_slug = excluded.parent_slug,
  parent_label = excluded.parent_label,
  seo = excluded.seo,
  breadcrumb = excluded.breadcrumb,
  hero = excluded.hero,
  hero_side = excluded.hero_side,
  hero_ctas = excluded.hero_ctas,
  spotlight = excluded.spotlight,
  sections = excluded.sections,
  sort_order = excluded.sort_order,
  published = excluded.published,
  updated_at = now();;
insert into public.product_pages (
  category_id, slug, page_type, parent_slug, parent_label,
  seo, breadcrumb, hero, hero_side, hero_ctas, spotlight, sections,
  sort_order, published
) values (
  'bde22157-f6e1-41df-b0db-89207ee6f899',
  'ceramic-structural',
  'category',
  null,
  null,
  '{"title":"Ceramic Structural Components | Shafts, Turbines & Seals","description":"Precision ceramic structural components, including shafts, wear parts, turbines, and custom-engineered solutions, from stock or custom-built within 14 days.","keywords":"structural ceramics"}'::jsonb,
  '[{"label":"Home","to":"/"},{"label":"Products","to":"/products"},{"label":"Ceramic Structural Parts"}]'::jsonb,
  '{"eyebrow":"Product Category 03 · Structural Engineering","title":"Ceramic structural parts,","titleHighlight":"12 sub-types.","subtitle":"Si₃N₄, SiC, Al₂O₃, AlN, and ZrO₂ precision structural components for <b>shafts, turbines, wear parts, seals, and custom machined geometries</b>. Drop-in and custom-to-drawing for semiconductor, aerospace, foundry, chemical, and precision machinery applications.","stats":[{"num":"12","lbl":"Sub-Types"},{"num":"5","lbl":"Materials"},{"num":"±0.01mm","lbl":"Tolerance"},{"num":"14d","lbl":"Prototype"}]}'::jsonb,
  'quote',
  null,
  null,
  '[{"type":"anchor-specs","id":"cutting-blade-specs","num":"01b · Cutting Blade Specifications","headingHtml":"Si₃N₄ high-speed cutting blades — <span class=\"accent\">reference dimensions</span>.","lead":"Ultra-thin silicon nitride ceramic blades for lithium battery film, cigarette tin foil, and other precision thin-material cutting. Dimensions below are reference values — actual parameters are adjusted per application.","items":[{"title":"Applications","body":"High-speed cutting of lithium battery films, cigarette tin foil, and other thin materials. Suitable for micron-level film cutting and precision thin-film applications."},{"title":"Performance","body":"Fast cutting speed, clean cutting without damaging the material, high-temperature resistance, long service life, high hardness, wear resistance, good chemical stability, and low friction coefficient."}],"table":{"headers":["Parameter","Typical Value","Notes"],"rows":[["Material","Silicon Nitride (Si₃N₄)","Ultra-thin ceramic construction"],["Thickness","3.9 mm","Reference dimension"],["Width × Length","16.9 × 80 mm","Also available: 17 × 92.5 mm"],["Custom sizes","Per drawing","Ultra-thin variants available on request"]]}},{"type":"benefits","num":"02 · Why Ceramitell for Structural Parts","headingHtml":"What precision engineers <span class=\"accent\">come to us for</span>.","lead":"Direct manufacturer. All five major structural ceramic materials. DFM support for custom geometries.","softBg":true,"items":[{"title":"Five materials, one supplier","body":"Si₃N₄, SiC, Al₂O₃, AlN, and ZrO₂ structural components from one factory. Match each sub-type to the right material chemistry without managing multiple suppliers."},{"title":"Tolerances to ±0.01mm","body":"Ground ceramic dimensions to ±0.01mm on critical features. Full CMM inspection reports for OEM qualification and aerospace programs."},{"title":"Prototype in 14 days","body":"DFM review within 48 hours of drawing receipt. Fired, inspected, and delivered prototypes in 7–14 days. No MOQ on first-article quantities."},{"title":"Custom geometries welcome","body":"Internal channels, threaded inserts, asymmetric profiles, and tight-tolerance bores — we quote what standard suppliers decline. Send any STEP, DWG, or PDF."},{"title":"Proven in demanding applications","body":"Si₃N₄ shaft rods in high-speed CNC spindles, lift tubes in aluminium die-casting running 1600°C, turbine components in turbocharger test programmes."},{"title":"ISO 9001 quality system","body":"Full material certs, dimensional reports, and PPAP documentation available for production qualifications. Lot traceability standard."}]},{"type":"app-uses","num":"03 · Applications","headingHtml":"Where ceramic structural parts <span class=\"accent\">outperform metal</span>.","lead":"Any application where metal fails due to temperature, corrosion, wear, weight, or magnetic interference.","items":[{"icon":"💻","title":"Semiconductor & Electronics","desc":"Si₃N₄ wafer-handling fixtures, AlN substrates, and Al₂O₃ susceptors for CVD/PVD tools and lithography stages.","grade":"Shafts · Plates · Substrates","to":"/applications/app-semiconductor"},{"icon":"✈️","title":"Aerospace & Defense","desc":"Si₃N₄ turbine components, B₄C armor tiles, and gyroscope bearing races for aerospace and defense OEMs.","grade":"Turbines · Shafts · Custom","to":"/applications/app-aerospace"},{"icon":"🏭","title":"Metallurgy & Foundry","desc":"Si₃N₄ lift tubes and thermocouple protection tubes for low-pressure aluminium die-casting and metal heat treatment.","grade":"Lift Tubes · Protection Tubes","to":"/applications/app-metallurgy"},{"icon":"⚗️","title":"Chemical & Fluid Control","desc":"SiC and Al₂O₃ seal faces, valve seats, and plungers for corrosive and abrasive slurry applications.","grade":"Seals · Plungers · Valves","to":"/applications/app-chemical-processing"},{"icon":"🔬","title":"Laboratory & Instruments","desc":"Al₂O₃ tubes, crucibles, and thermocouple sheaths for analytical instruments and tube furnaces.","grade":"Tubes · Substrates · Custom","to":"/applications/app-laboratory"},{"icon":"📐","title":"Your Application","desc":"Any ceramic structural need not listed — send your drawing or describe your application and we''ll recommend material and geometry.","grade":"Talk to an engineer","to":"/contact"}]},{"type":"faq","num":"04 · FAQ","headingHtml":"The questions <span class=\"accent\">we get most</span>.","softBg":true,"items":[{"q":"Which ceramic material should I use for my shaft application?","a":"Si₃N₄ for high-speed, high-load, and non-magnetic requirements. SiC for highest hardness and corrosion resistance. Al₂O₃ for cost-sensitive moderate-load applications. Send your operating conditions — we''ll recommend."},{"q":"What is the tightest tolerance you can hold?","a":"Ground ceramic: ±0.01mm on critical dimensions. As-fired: ±0.5% of nominal. CMM inspection reports available for all production parts."},{"q":"How quickly can I get a prototype?","a":"DFM review within 48 hours of drawing receipt. Prototype lead time: 7–14 days from drawing approval. No MOQ on prototypes."},{"q":"Can you machine complex internal features?","a":"Yes — internal channels, cross-holes, threaded bores, and undercuts are all achievable. Green machining before sintering enables complex profiles that are impossible to grind post-fire."},{"q":"What is the MOQ for production parts?","a":"Simple geometries: 500 units. Complex or tight-tolerance parts: 200 units. Custom special profiles: quote-dependent. Volume pricing from 2,000 units."},{"q":"Do you provide NDA and confidentiality protection?","a":"Yes — mutual NDA standard before any drawing exchange. We have maintained full customer confidentiality across all OEM programs since 2014."}]},{"type":"casecta"}]'::jsonb,
  2,
  true
) on conflict (slug) do update set
  category_id = excluded.category_id,
  page_type = excluded.page_type,
  parent_slug = excluded.parent_slug,
  parent_label = excluded.parent_label,
  seo = excluded.seo,
  breadcrumb = excluded.breadcrumb,
  hero = excluded.hero,
  hero_side = excluded.hero_side,
  hero_ctas = excluded.hero_ctas,
  spotlight = excluded.spotlight,
  sections = excluded.sections,
  sort_order = excluded.sort_order,
  published = excluded.published,
  updated_at = now();;
insert into public.product_pages (
  category_id, slug, page_type, parent_slug, parent_label,
  seo, breadcrumb, hero, hero_side, hero_ctas, spotlight, sections,
  sort_order, published
) values (
  '61cd3349-32f5-4f04-8431-73212ff015bf',
  'custom-ceramic',
  'category',
  null,
  null,
  '{"title":"Custom Ceramic Components | DFM, Prototyping & Production","description":"Custom ceramic components to your drawing, with DFM review in 48 hours, prototypes in 14 days, and across six ceramic materials. No geometry is too complex.","keywords":"custom ceramic parts"}'::jsonb,
  '[{"label":"Home","to":"/"},{"label":"Products","to":"/products"},{"label":"Custom Ceramic Components"}]'::jsonb,
  '{"eyebrow":"Product Category 04 · Custom Manufacturing","title":"Custom ceramic components,","titleHighlight":"to your drawing.","subtitle":"From concept sketch to fired ceramic in <b>14 days</b>. STEP, DWG, and PDF across Si₃N₄, SiC, Al₂O₃, AlN, ZrO₂, and B₄C. No geometry is too complex.","stats":[{"num":"48h","lbl":"DFM Review"},{"num":"14d","lbl":"Prototype"},{"num":"6","lbl":"Materials"},{"num":"Any","lbl":"Geometry"}]}'::jsonb,
  'quote',
  null,
  null,
  '[{"type":"benefits","num":"02 · Why Ceramitell for Custom Parts","headingHtml":"What precision engineers <span class=\"accent\">come to us for</span>.","lead":"We make the part you can''t find off the shelf.","softBg":true,"items":[{"title":"DFM-first approach","body":"We flag manufacturability issues before you commit to tooling — saving re-design cycles."},{"title":"All six ceramic materials","body":"One partner for Si₃N₄, SiC, Al₂O₃, AlN, ZrO₂, and B₄C — no need to manage separate suppliers."},{"title":"Complex geometries","body":"Thin walls, internal channels, precision bores, threaded inserts — we quote what standard suppliers won''t."},{"title":"Fastest prototype in category","body":"7–14 days from drawing approval to fired, inspected, delivered prototype."},{"title":"Tolerances to ±0.01mm","body":"Grinding to ±0.01mm on critical dimensions. Full CMM inspection reports for qualification."},{"title":"Confidentiality guaranteed","body":"Mutual NDA before any drawing exchange. Zero geometry leaks across 10 years of OEM programs."}]},{"type":"app-uses","num":"03 · Custom Ceramic Applications","headingHtml":"Industries that rely on <span class=\"accent\">custom ceramic parts</span>.","lead":"If it needs to survive extreme temperature, corrosion, or wear — and metal won''t do it — we can make it in ceramic.","items":[{"icon":"💻","title":"Semiconductor","desc":"Si₃N₄ wafer-handling fixtures, Al₂O₃ susceptors, and AlN substrates to semiconductor tool drawings.","grade":"Custom to drawing","to":"/applications"},{"icon":"✈️","title":"Aerospace & Defense","desc":"B₄C armor tiles, Si₃N₄ bearing races, and gyroscope components. ITAR-compliant handling available.","grade":"Custom to drawing","to":"/applications"},{"icon":"⚗️","title":"Chemical & Fluid Control","desc":"Al₂O₃ valve seats, SiC seal faces, ZrO₂ pump impellers for corrosive media.","grade":"Custom to drawing","to":"/applications"},{"icon":"🔬","title":"Laboratory Instruments","desc":"Custom Al₂O₃ crucibles, thermocouple sheaths, ICP-OES atomization tubes.","grade":"Custom to drawing","to":"/applications"},{"icon":"🏭","title":"Industrial & Foundry","desc":"Si₃N₄ lift tubes, thermocouple protection tubes, AlN crucibles for casting and heat treatment.","grade":"Custom to drawing","to":"/applications"},{"icon":"📐","title":"Your Application","desc":"Send any drawing — feasibility, material recommendation, and quote within 48 hours.","grade":"Submit your drawing","to":"/applications"}]},{"type":"faq","num":"04 · FAQ","headingHtml":"The questions <span class=\"accent\">we get most</span>.","softBg":true,"items":[{"q":"What file formats?","a":"STEP, IGES, DWG, DXF, PDF (dimensioned). Solidworks/Rhino native files. Sketches with dimensions for preliminary feasibility."},{"q":"Which material is right?","a":"Tell us operating temperature, chemical environment, loads, and tolerances — our DFM team recommends and explains trade-offs."},{"q":"Minimum order?","a":"Prototypes: no MOQ (single-unit quotes available). Production: typically 500 units simple, 200 units complex geometry."},{"q":"Tolerance capability?","a":"Ground ceramic: ±0.01mm. As-fired: ±0.5%. Green-machined: ±0.1–0.2mm."},{"q":"NDA before sending drawings?","a":"Yes — mutual NDA standard before any drawing exchange."},{"q":"What documentation is supplied?","a":"Prototype: dimensional report, material cert, photos. Production: first-article inspection, dimensional sample, material cert. SPC and PPAP on request."}]},{"type":"casecta"}]'::jsonb,
  3,
  true
) on conflict (slug) do update set
  category_id = excluded.category_id,
  page_type = excluded.page_type,
  parent_slug = excluded.parent_slug,
  parent_label = excluded.parent_label,
  seo = excluded.seo,
  breadcrumb = excluded.breadcrumb,
  hero = excluded.hero,
  hero_side = excluded.hero_side,
  hero_ctas = excluded.hero_ctas,
  spotlight = excluded.spotlight,
  sections = excluded.sections,
  sort_order = excluded.sort_order,
  published = excluded.published,
  updated_at = now();;
insert into public.product_pages (
  category_id, slug, page_type, parent_slug, parent_label,
  seo, breadcrumb, hero, hero_side, hero_ctas, spotlight, sections,
  sort_order, published
) values (
  '977d75b6-1731-4935-8b6b-dd3e8b3a1b01',
  'ceramic-balls',
  'category',
  null,
  null,
  '{"title":"Precision Ceramic Balls | G3–G60 Bearing Ball Solutions","description":"Precision ceramic balls in silicon nitride and zirconia grades, available from G3–G60 and Ø0.4–100mm for bearings, aerospace, and industrial applications.","keywords":"ceramic balls, ceramic ball, ceramic ball bearings, ceramic ball bearing, bearing ceramic ball, china ceramic ball, chinese ceramic balls"}'::jsonb,
  '[{"label":"Home","to":"/"},{"label":"Products","to":"/products"},{"label":"Ceramic Balls"}]'::jsonb,
  '{"eyebrow":"Product Category 05 · Precision Balls","title":"Precision ceramic balls,","titleHighlight":"Si₃N₄ and ZrO₂.","subtitle":"Bearing-grade ceramic balls for precision bearings, ball screws, pumps, valves, and check valves. Grade <b>G3 to G60</b>, diameter 0.4mm to 100mm. Si₃N₄ (lighter, harder) and ZrO₂ (denser, tougher) from stock.","stats":[{"num":"G3–G60","lbl":"Grade Range"},{"num":"0.4–100mm","lbl":"Diameter"},{"num":"2 Materials","lbl":"Si₃N₄ & ZrO₂"},{"num":"P0–P5","lbl":"Bearing Precision"}]}'::jsonb,
  'quote',
  null,
  null,
  '[{"type":"grade-guide","num":"02 · Grade Guide","headingHtml":"Choosing the right <span class=\"accent\">grade</span>.","lead":"ISO 3290 grade number = max allowable deviation in micrometres. Lower grade = tighter tolerance = higher precision. Choose based on your bearing accuracy class (P0–P5) and operating speed.","softBg":true,"items":[{"title":"G3 / G5 — Precision Bearing Grade","body":"For high-precision angular contact bearings, spindle bearings, and gyroscope bearings. Max deviation ≤0.08µm (G3). Aerospace and semiconductor spindle applications."},{"title":"G10 / G16 — High-Precision Grade","body":"Standard for P4 and P2 bearing accuracy class. CNC spindle bearings, dental turbines, and precision instrument bearings."},{"title":"G25 / G40 — Standard Engineering Grade","body":"General-purpose bearings, ball screws, and pump check valves. P0–P6 accuracy class. Cost-effective for high-volume industrial applications."},{"title":"G60 — Commercial Grade","body":"For valve seats, flow metering, and applications where chemical or thermal resistance matters more than roundness tolerance."}]},{"type":"app-uses","num":"03 · Applications","headingHtml":"Where ceramic balls <span class=\"accent\">outperform steel</span>.","lead":"Any bearing, pump, or valve that fails in steel due to speed, temperature, corrosion, or magnetism.","items":[{"icon":"⚙️","title":"Precision Bearings","desc":"Si₃N₄ balls for angular contact, deep groove, and hybrid ceramic bearings. 3× longer life vs steel at high speed.","grade":"Si₃N₄ G3–G16","to":"/applications"},{"icon":"🔩","title":"Ball Screws","desc":"Ceramic balls for CNC and semiconductor lithography ball screws. Zero stick-slip, lubrication-free.","grade":"Si₃N₄ G10–G25","to":"/applications"},{"icon":"💧","title":"Pumps & Valves","desc":"ZrO₂ balls for check valves and pump seats in corrosive chemical and food-process environments.","grade":"ZrO₂ G25–G60","to":"/applications"},{"icon":"🔬","title":"Medical & Dental","desc":"Si₃N₄ balls for dental turbines and surgical instrument bearings. Biocompatible, autoclavable.","grade":"Si₃N₄ G5–G16","to":"/applications"},{"icon":"✈️","title":"Aerospace","desc":"G3 Si₃N₄ balls for gyroscope and navigation system bearings. Zero magnetic signature.","grade":"Si₃N₄ G3–G5","to":"/applications"},{"icon":"🏭","title":"Grinding Media","desc":"ZrO₂ balls for wet and dry milling of ceramic slurries, pigments, and battery materials.","grade":"ZrO₂ G40–G60","to":"/applications"}]},{"type":"faq","num":"04 · FAQ","headingHtml":"The questions <span class=\"accent\">we get most</span>.","softBg":true,"items":[{"q":"Grade for my bearing?","a":"Match to accuracy class: P2→G5, P4→G10–G16, P5→G16–G25, P0→G25–G60. Send bearing model number to confirm."},{"q":"MOQ?","a":"Stock sizes: no MOQ for samples. Custom <5mm: 200pc min. Large diameter >50mm: quote on request."},{"q":"Si₃N₄ vs ZrO₂?","a":"Si₃N₄: lighter (3.2 g/cm³), harder (HRC 78), better for high-speed/high-temp. ZrO₂: denser (6.0), tougher, better for corrosive media."},{"q":"Surface finish?","a":"Standard Ra ≤0.01µm (mirror). Custom Ra to specification. Lapping to P2/G3 on request."},{"q":"Stock availability?","a":"Common bearing ball sizes in both materials held in stock. Standard sizes dispatch within 48h."},{"q":"Aerospace/medical certs?","a":"Material cert with every shipment. XRF analysis available. AS9100 and medical traceability on OEM programs."}]},{"type":"casecta"}]'::jsonb,
  4,
  true
) on conflict (slug) do update set
  category_id = excluded.category_id,
  page_type = excluded.page_type,
  parent_slug = excluded.parent_slug,
  parent_label = excluded.parent_label,
  seo = excluded.seo,
  breadcrumb = excluded.breadcrumb,
  hero = excluded.hero,
  hero_side = excluded.hero_side,
  hero_ctas = excluded.hero_ctas,
  spotlight = excluded.spotlight,
  sections = excluded.sections,
  sort_order = excluded.sort_order,
  published = excluded.published,
  updated_at = now();;
insert into public.product_pages (
  category_id, slug, page_type, parent_slug, parent_label,
  seo, breadcrumb, hero, hero_side, hero_ctas, spotlight, sections,
  sort_order, published
) values (
  'd00a34fe-efb2-4fde-a1eb-3789666d682d',
  'precision-bearings',
  'category',
  null,
  null,
  '{"title":"Precision Ceramic Bearings | Full Ceramic & Hybrid Bearings","description":"Precision ceramic bearings in full ceramic and hybrid for motors, pumps, and high-speed equipment requiring corrosion resistance and electrical insulation.","keywords":"ceramic bearings, ceramic bearing, hybrid ceramic bearings, bearing ceramic hybrid, ceramic vs steel bearings, ceramic skateboard bearings, ceramic skate bearings, ceramic wheel bearings, bones ceramic bearings"}'::jsonb,
  '[{"label":"Home","to":"/"},{"label":"Products","to":"/products"},{"label":"Precision Ceramic Bearings"}]'::jsonb,
  '{"eyebrow":"Product Category 06 · Precision Bearings","title":"Precision ceramic bearings,","titleHighlight":"full and hybrid.","subtitle":"Full and hybrid ceramic ball bearings for <b>high-speed, high-temperature, and corrosive environments</b>. Four types cover wind turbine generators, CNC spindles, semiconductor stages, and aerospace gyroscopes. Precision P0 to P5.","stats":[{"num":"4","lbl":"Bearing Types"},{"num":"3–250mm","lbl":"Bore Diameter"},{"num":"P0–P5","lbl":"Precision Class"},{"num":"100K+","lbl":"RPM Capable"}]}'::jsonb,
  'quote',
  null,
  null,
  '[{"type":"benefits","num":"02 · Why Ceramic Bearings","headingHtml":"When steel bearings <span class=\"accent\">reach their limit</span>.","lead":"Ceramic bearings solve four specific problems that steel cannot.","softBg":true,"items":[{"title":"3× longer life at high speed","body":"Si₃N₄ balls are 60% lighter than steel — at 100,000+ RPM the reduced centrifugal force dramatically extends bearing life."},{"title":"Lubrication-free operation","body":"Full ceramic bearings run dry in vacuum, clean rooms, and food/pharma where lubricant contamination is unacceptable."},{"title":"Resistant to corrosive media","body":"Zirconia bearings operate in concentrated acid, alkali, and seawater where steel corrodes within hours."},{"title":"Non-magnetic and electrically insulating","body":"Si₃N₄ has zero magnetic permeability — mandatory in MRI equipment and magnetic measurement instruments."},{"title":"High-temperature operation","body":"Full Si₃N₄ bearings operate to 800°C continuously — steel requires relubrication above 150°C."},{"title":"Applications: wind, CNC, aerospace","body":"Wind turbine main shaft bearings, CNC spindles, aerospace gyroscopes — we supply all three."}]},{"type":"app-uses","num":"03 · Applications","headingHtml":"Where ceramic bearings <span class=\"accent\">are specified</span>.","lead":"Any application where speed, temperature, corrosion, or magnetism exceeds steel bearing limits.","items":[{"icon":"💨","title":"Wind Power","desc":"Full Si₃N₄ main shaft and generator bearings for wind turbines. Lubrication-free, 20-year design life.","grade":"Full Si₃N₄ P0–P5","to":"/applications"},{"icon":"🔧","title":"CNC Machining","desc":"Si₃N₄ hybrid spindle bearings for machining centres. 40,000–100,000 RPM.","grade":"Si₃N₄ Hybrid P2–P4","to":"/applications"},{"icon":"✈️","title":"Aerospace & Gyroscopes","desc":"Full Si₃N₄ for inertial navigation gyroscopes and satellite reaction wheels. Non-magnetic.","grade":"Full Si₃N₄ G3–G5","to":"/applications"},{"icon":"⚗️","title":"Chemical & Pharmaceutical","desc":"ZrO₂ full ceramic for pumps and agitators in aggressive chemical environments.","grade":"Full ZrO₂ P0–P5","to":"/applications"},{"icon":"🏥","title":"Medical Equipment","desc":"Full Si₃N₄ for MRI-compatible surgical robots and dental turbines. Non-magnetic, sterilisable.","grade":"Full Si₃N₄ P2–P4","to":"/applications"},{"icon":"🔋","title":"Clean Energy","desc":"Si₃N₄ hybrid bearings for fuel cell compressors and battery slurry pumps.","grade":"Si₃N₄ Hybrid","to":"/applications"}]},{"type":"faq","num":"04 · FAQ","headingHtml":"The questions <span class=\"accent\">we get most</span>.","softBg":true,"items":[{"q":"What precision class do I need?","a":"P0 general; P6 machine tool spindles; P5/P4 high-speed CNC; P2 precision instruments. Send bore/OD/RPM — we''ll recommend."},{"q":"Full ceramic vs hybrid?","a":"Hybrid: lower cost, high speed, clean environments. Full ceramic: corrosive media, high temp, magnetic sensitivity."},{"q":"Non-standard sizes?","a":"Custom bore/OD/width to drawing. Standard 6xxx/7xxx series in ceramic from size charts. Custom: 4–8 weeks."},{"q":"Lubrication requirements?","a":"Full ceramic: run dry or minimal lube. Hybrid: standard grease or oil-air. Grease type recommended per speed and temperature."},{"q":"Sample lead time?","a":"Standard Si₃N₄ hybrid: 1–2 weeks. Full ceramic standard: 2–4 weeks. Custom: 6–10 weeks."},{"q":"Documentation?","a":"Material cert, dimensional report, bearing accuracy cert standard. PPAP, first-article, and engineering support for OEM programs."}]},{"type":"casecta"}]'::jsonb,
  5,
  true
) on conflict (slug) do update set
  category_id = excluded.category_id,
  page_type = excluded.page_type,
  parent_slug = excluded.parent_slug,
  parent_label = excluded.parent_label,
  seo = excluded.seo,
  breadcrumb = excluded.breadcrumb,
  hero = excluded.hero,
  hero_side = excluded.hero_side,
  hero_ctas = excluded.hero_ctas,
  spotlight = excluded.spotlight,
  sections = excluded.sections,
  sort_order = excluded.sort_order,
  published = excluded.published,
  updated_at = now();;
insert into public.product_pages (
  category_id, slug, page_type, parent_slug, parent_label,
  seo, breadcrumb, hero, hero_side, hero_ctas, spotlight, sections,
  sort_order, published
) values (
  '25f56cfd-ee23-45d9-894a-cd01504c7852',
  'grinding-media',
  'category',
  null,
  null,
  '{"title":"Ceramic Grinding Media | Silicon Nitride & Zirconia Balls","description":"High-density ceramic grinding media in Si₃N₄ or ZrO₂ type for wet and dry milling, zero metal contamination, battery materials, and high-purity powders.","keywords":"ceramic grinding media"}'::jsonb,
  '[{"label":"Home","to":"/"},{"label":"Products","to":"/products"},{"label":"Grinding Media"}]'::jsonb,
  '{"eyebrow":"Product Category 07 · Grinding Media","title":"Ceramic grinding media,","titleHighlight":"Si₃N₄ and ZrO₂.","subtitle":"High-density ceramic grinding balls and beads for <b>wet and dry milling</b> of battery cathode materials, pigments, coatings, and mineral slurries. Zero metal contamination — critical for battery and electronics applications.","stats":[{"num":"2","lbl":"Media Types"},{"num":"0.4–100mm","lbl":"Bead Size"},{"num":"Zero","lbl":"Metal Contamination"},{"num":"Battery-Grade","lbl":"Purity"}]}'::jsonb,
  'quote',
  null,
  null,
  '[{"type":"benefits","num":"02 · Why Ceramic Grinding Media","headingHtml":"Why ceramic media <span class=\"accent\">replaces steel</span>.","lead":"Metal contamination ruins battery electrode performance. Ceramic media eliminates the risk.","softBg":true,"items":[{"title":"Zero iron contamination","body":"Steel media contaminate battery slurries with Fe ions that degrade cathode performance. Ceramic media contributes zero metal ions."},{"title":"Longer media life","body":"Si₃N₄ outlasts alumina 3–5× and steel 10–20× in hard abrasive slurries — lower total cost of ownership."},{"title":"Higher milling energy (ZrO₂)","body":"ZrO₂ density 6.0 g/cm³ vs alumina 3.9 g/cm³ — more impact energy per ball, reducing milling time."},{"title":"Consistent particle size distribution","body":"Uniform sphericity and low size variance give reproducible D50 — critical for battery electrode control."},{"title":"Battery, coatings, mining applications","body":"LFP/NMC cathode slurry, lithium carbonate, pigment dispersions, TiO₂, and mineral concentrates."},{"title":"Stock in all standard sizes","body":"0.4mm to 100mm across both materials. Stock sizes dispatch within 48 hours."}]},{"type":"app-uses","num":"03 · Applications","headingHtml":"What our customers <span class=\"accent\">mill with ceramic</span>.","lead":"Battery materials, pigments, coatings, minerals — any slurry where contamination, purity, or wear life is critical.","items":[{"icon":"🔋","title":"Battery Materials","desc":"NMC/LFP cathode slurry, lithium carbonate, and solid-state electrolyte powder milling. Zero Fe contamination critical.","grade":"ZrO₂ or Si₃N₄","to":"/applications"},{"icon":"🎨","title":"Pigments & Coatings","desc":"TiO₂, carbon black, and organic pigment dispersions for paints, inks, and coatings.","grade":"ZrO₂","to":"/applications"},{"icon":"⛏️","title":"Mining & Minerals","desc":"Hard mineral concentration and ceramic powder milling — silica, alumina, and advanced ceramic feedstocks.","grade":"Si₃N₄","to":"/applications"},{"icon":"💊","title":"Pharmaceutical & Food","desc":"Particle size reduction for drug formulation and food ingredient processing.","grade":"ZrO₂","to":"/applications"},{"icon":"🔬","title":"Advanced Ceramics","desc":"Milling of ceramic precursor powders for sintering — Si₃N₄, SiC, AlN, ZrO₂ feedstock.","grade":"Si₃N₄","to":"/applications"},{"icon":"⚗️","title":"Chemical Processing","desc":"Catalyst milling, chemical reaction intermediates, and specialty dispersion applications.","grade":"ZrO₂ or Si₃N₄","to":"/applications"}]},{"type":"faq","num":"04 · FAQ","headingHtml":"The questions <span class=\"accent\">we get most</span>.","softBg":true,"items":[{"q":"Which media for battery cathode?","a":"ZrO₂ standard for NMC/LFP slurry. Si₃N₄ for ultra-high-purity or very hard feed materials."},{"q":"What bead size?","a":"Typically 10× the feed D90. For D50 < 1µm, use beads ≤0.5mm. Send feed size and target — we''ll recommend."},{"q":"Lead time?","a":"Common sizes in stock: 48h. Non-stock: 2–4 weeks. Sample 1kg: no MOQ."},{"q":"Media load calculation?","a":"Standard fill 50–60% of mill volume. ZrO₂ (6.0 g/cm³) loads heavier than alumina — we''ll advise on your mill."},{"q":"Documentation?","a":"Material cert with every shipment. XRF purity analysis available. Trace metal content cert for battery manufacturer qualification."},{"q":"Wear rate vs alumina?","a":"ZrO₂ wear rate typically 3–5× lower than alumina. Si₃N₄: 5–10× lower. Less contamination, longer intervals."}]},{"type":"casecta"}]'::jsonb,
  6,
  true
) on conflict (slug) do update set
  category_id = excluded.category_id,
  page_type = excluded.page_type,
  parent_slug = excluded.parent_slug,
  parent_label = excluded.parent_label,
  seo = excluded.seo,
  breadcrumb = excluded.breadcrumb,
  hero = excluded.hero,
  hero_side = excluded.hero_side,
  hero_ctas = excluded.hero_ctas,
  spotlight = excluded.spotlight,
  sections = excluded.sections,
  sort_order = excluded.sort_order,
  published = excluded.published,
  updated_at = now();;
insert into public.product_pages (
  category_id, slug, page_type, parent_slug, parent_label,
  seo, breadcrumb, hero, hero_side, hero_ctas, spotlight, sections,
  sort_order, published
) values (
  'ab2b0569-e7d6-4b83-9329-77c2364452f1',
  'ceramic-powder',
  'category',
  null,
  null,
  '{"title":"Superfine Ceramic Powder | High-Purity Si₃N₄ & ZrO₂ Powders","description":"High-purity ceramic powders with ≥99.5% purity and custom D50 distributions for advanced ceramics manufacturing, thermal spray coatings, and research.","keywords":"ceramic powder"}'::jsonb,
  '[{"label":"Home","to":"/"},{"label":"Products","to":"/products"},{"label":"Ceramic Powder"}]'::jsonb,
  '{"eyebrow":"Product Category 08 · Ceramic Powder","title":"Superfine ceramic powder,","titleHighlight":"Si₃N₄ and ZrO₂.","subtitle":"High-purity superfine ceramic powders for <b>advanced ceramics manufacturing</b>, thermal spray coatings, and research applications. Purity ≥99.5%, custom D50 distributions, batch-to-batch consistency.","stats":[{"num":"≥99.5%","lbl":"Purity"},{"num":"2","lbl":"Powder Grades"},{"num":"Custom D50","lbl":"Available"},{"num":"Research-Grade","lbl":"Quality"}]}'::jsonb,
  'quote',
  null,
  null,
  '[{"type":"benefits","num":"02 · Why Our Ceramic Powders","headingHtml":"What R&D engineers and <span class=\"accent\">manufacturers need</span>.","lead":"Consistent chemistry, controlled particle size, and full traceability.","softBg":true,"items":[{"title":"Purity ≥99.5%","body":"Batch-certified by XRF analysis. Trace element content reported per shipment — critical for semiconductor and optical applications."},{"title":"Custom particle size distributions","body":"D50 from 0.3µm to 5µm, D90 to specification. Jet milling and classification to your particle size target."},{"title":"Batch-to-batch consistency","body":"ISO 9001 process control with lot traceability. Phase composition (α/β ratio for Si₃N₄) certified per batch."},{"title":"Research to production scale","body":"Sample from 100g. Production from 50kg. Scale-up without chemistry change — critical for R&D-to-product transition."},{"title":"Technical support","body":"Our ceramic engineers advise on sintering conditions, binder systems, and pressing parameters."},{"title":"Fast sample dispatch","body":"Standard grades dispatch within 48 hours. Non-standard D50: 2–3 weeks."}]},{"type":"app-uses","num":"03 · Applications","headingHtml":"What our powders are used for.","lead":"From sintered structural ceramics to thermal spray coatings — wherever powder quality determines end-product performance.","items":[{"icon":"🏭","title":"Advanced Ceramics Sintering","desc":"Si₃N₄ and ZrO₂ powder for pressing and sintering of structural and functional ceramic components.","grade":"Si₃N₄ or ZrO₂","to":"/applications"},{"icon":"🦷","title":"Dental Ceramics","desc":"3Y-TZP ZrO₂ for CAD/CAM dental crowns and bridges. Consistent shrinkage and translucency.","grade":"ZrO₂ 3Y-TZP","to":"/applications"},{"icon":"⚡","title":"Solid Oxide Fuel Cells","desc":"8Y-TZP ZrO₂ electrolyte powder for SOFC tape casting and screen printing.","grade":"ZrO₂","to":"/applications"},{"icon":"🔬","title":"Research & Development","desc":"Controlled particle size and chemistry for ceramic R&D and novel composite materials.","grade":"Si₃N₄ or ZrO₂","to":"/applications"},{"icon":"🌡️","title":"Thermal Spray Coatings","desc":"Si₃N₄ and ZrO₂ powders for HVOF and plasma spray thermal barrier coatings.","grade":"Si₃N₄ or ZrO₂","to":"/applications"},{"icon":"⚗️","title":"Composite Reinforcement","desc":"Si₃N₄ whisker and particulate reinforcement for metal and ceramic matrix composites.","grade":"Si₃N₄","to":"/applications"}]},{"type":"faq","num":"04 · FAQ","headingHtml":"The questions <span class=\"accent\">we get most</span>.","softBg":true,"items":[{"q":"Phase for Si₃N₄ powder?","a":"Standard: α-phase >90%. β-phase and α/β blended grades available — specify sintering route. Phase cert with each batch."},{"q":"Stabiliser for ZrO₂?","a":"Standard: 3 mol% Y₂O₃ (3Y-TZP) for structural/dental. 8Y-TZP for thermal barrier/SOFC. Unstabilised available."},{"q":"Minimum order?","a":"Sample: 100g, no charge for qualification. Production: 5kg minimum. Bulk pricing from 50kg."},{"q":"Particle size analysis?","a":"Laser diffraction D10/D50/D90 report with every shipment. Custom PSD targets: specify D50 and D90 at order."},{"q":"Documentation?","a":"Certificate of analysis (purity, PSD, phase), SDS, lot traceability standard. ICP-MS trace element analysis available."},{"q":"Non-standard compositions?","a":"Doped ZrO₂, Si₃N₄ with pre-mixed sintering aids, and custom chemistries available with minimum order."}]},{"type":"casecta"}]'::jsonb,
  7,
  true
) on conflict (slug) do update set
  category_id = excluded.category_id,
  page_type = excluded.page_type,
  parent_slug = excluded.parent_slug,
  parent_label = excluded.parent_label,
  seo = excluded.seo,
  breadcrumb = excluded.breadcrumb,
  hero = excluded.hero,
  hero_side = excluded.hero_side,
  hero_ctas = excluded.hero_ctas,
  spotlight = excluded.spotlight,
  sections = excluded.sections,
  sort_order = excluded.sort_order,
  published = excluded.published,
  updated_at = now();;